# fly.toml

# Replace "thinksync" with the name you gave your app on Fly.io
# (e.g., the output of `fly apps create your-app-name`)
app = "thinksync"
primary_region = "cdg" # Choose a region, e.g., "sjc" (San Jose), "iad" (Ashburn), "lhr" (London)

# Kill signal and timeout for graceful shutdowns
kill_signal = "SIGINT"
kill_timeout = "5s" # FastAPI's default shutdown timeout

[build]
  # Fly.io will use your Dockerfile to build the image
  dockerfile = "Dockerfile"
  # You can add build-time arguments if your Dockerfile uses them
  # [build.args]
  #   SOME_BUILD_ARG = "value"

[env]
  # This PORT must match the port your Uvicorn server listens on inside the container
  PORT = "8000"
  LOG_LEVEL = "INFO" # Or "DEBUG", "WARNING", "ERROR" as set in your app
  # PYTHONUNBUFFERED and PYTHONDONTWRITEBYTECODE are already set in your Dockerfile, which is good.
  # For Gunicorn (see "Further Considerations" below), you might add:
  # WEB_CONCURRENCY = "2" # Example: 2 Gunicorn workers

# This section defines how Fly.io routes HTTP/HTTPS traffic to your app
[http_service]
  internal_port = 8000 # This must match the PORT Uvicorn is listening on
  force_https = true   # Recommended: Redirects HTTP to HTTPS
  auto_stop_machines = true  # Stops machines when idle to save costs (can be false)
  auto_start_machines = true # Starts machines on new requests
  min_machines_running = 0   # If auto_stop_machines is true; set to 1 for always-on

  # HTTP Health Checks
  # Fly.io uses these to determine if your app is healthy and can receive traffic.
  [[http_service.checks]]
    port = 8000 # Port for the health check, usually same as internal_port
    type = "http"
    method = "GET"
    # Your current "/" path is okay for a basic health check.
    # For a more robust check, consider adding a dedicated /healthz endpoint (see notes below).
    path = "/"
    interval = "15s" # How often to check
    timeout = "2s"   # How long to wait for a response
    grace_period = "10s" # Time to allow app to start before checks begin failing.
                        # Adjust based on your app's startup time.

# Define VM resources (optional, Fly.io picks defaults based on region/plan)
# [[vm]]
#  cpu_kind = "shared"
#  cpus = 1
#  memory_mb = 256 # Adjust memory as needed. Smallest is often 256MB.
